import org.codehaus.groovy.runtime.GStringImpl

plugins {
    id 'java'
    alias(libs.plugins.spotless)
    alias(libs.plugins.shadow)
    alias(libs.plugins.jvmdowngrader)
}

repositories {
    mavenCentral()
}


ext {
    namespace = "${rootProject.property('group')}.${rootProject.property('artifact')}" as GStringImpl
    javaToolchainVersion = "${rootProject.property('javaToolchainVersion')}"
    javaVersion = "${rootProject.property('javaVersion')}"
}

apply from: 'gradle/scripts/modules.gradle'
apply from: 'gradle/scripts/package.gradle'

spotless {
    java {
        target 'modules/*/src/*/java/**/*.java'
        palantirJavaFormat()
    }
}

tasks.named('check') {
    dependsOn 'spotlessCheck'
}