plugins {
    id 'java'
    alias(libs.plugins.spotless)
    alias(libs.plugins.shadow)
    alias(libs.plugins.jvmdowngrader)
}

ext {
    namespace = "${rootProject.property('group')}.${rootProject.property('artifact')}"
}

apply from: 'gradle/scripts/repositories.gradle'
apply from: 'gradle/scripts/modules.gradle'
apply from: 'gradle/scripts/spotless.gradle'
apply from: 'gradle/scripts/package.gradle'