group 'team.terrafirmagreg'
version '1.4.0'

allprojects {
    group = rootProject.group
    version = rootProject.version

    pluginManager.withPlugin('java') {
        repositories {
            mavenCentral()
            maven {
                name = 'intellij-repository'
                url = 'https://www.jetbrains.com/intellij-repository/releases/'
            }
        }

        configurations {
            compileOnly {
                extendsFrom annotationProcessor
            }
        }

        // Jabel stuff, compile with new java features while targeting java 8
        dependencies {
            annotationProcessor 'com.github.bsideup.jabel:jabel-javac-plugin:0.4.2'
            annotationProcessor 'org.projectlombok:lombok:1.18.46'
            compileOnly 'org.projectlombok:lombok:1.18.46'
            testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.1'
            testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.1'
        }

        configure([tasks.compileJava]) {
            sourceCompatibility = 17 // for the IDE support
            options.release = 8

            javaCompiler = javaToolchains.compilerFor {
                languageVersion = JavaLanguageVersion.of(17)
            }
        }

        compileTestJava {
            sourceCompatibility = targetCompatibility = 8
        }

        test {
            useJUnitPlatform()
            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(8)
            }
        }
    }

    pluginManager.withPlugin('application') {
        run {
            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(8)
            }
        }
    }
}
