plugins {
    id 'java-library'
}

repositories {
    maven {
        name "neoforged"
        url "https://maven.neoforged.net/releases"
    }
}

dependencies {
    implementation project(':core')
    compileOnly "cpw.mods:modlauncher:2.1.5"
    compileOnly "org.apache.logging.log4j:log4j-api:2.20.0"
}
