package team.terrafirmagreg.autopack.ui.page;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import team.terrafirmagreg.autopack.UnsafeExit;
import team.terrafirmagreg.autopack.i18n.Messages;
import team.terrafirmagreg.autopack.ui.components.ScrollablePane;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicBoolean;

public class PakkuPromptPage extends JPanel {
    private final CountDownLatch latch = new CountDownLatch(1);
    private final AtomicBoolean accepted = new AtomicBoolean(false);
    private JPanel root;
    private JLabel pageTitle;
    private JLabel info;
    private JPanel content;
    private JButton yesButton;
    private JButton noButton;
    private JButton cancelAndExitButton;

    public PakkuPromptPage(Messages messages, String titleKey, String messageKey, List<String> entries) {
        $$$setupUI$$$();
        pageTitle.setText(messages.get(titleKey));
        info.setText(asHtml(messages.get(messageKey)));
        yesButton.setText(messages.get("autopack.pakku.yes"));
        noButton.setText(messages.get("autopack.pakku.no"));
        cancelAndExitButton.setText(messages.get("autopack.pakku.cancel"));

        setLayout(new BorderLayout());
        add(root, BorderLayout.CENTER);

        yesButton.addActionListener(e -> {
            accepted.set(true);
            latch.countDown();
        });
        noButton.addActionListener(e -> {
            accepted.set(false);
            latch.countDown();
        });
        cancelAndExitButton.addActionListener(e -> UnsafeExit.exit(0));

        for (String entry : entries) {
            content.add(new JLabel(asHtml(entry)));
        }
    }

    private void createUIComponents() {
        content = new ScrollablePane(true, false);
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));
    }

    private String asHtml(String text) {
        return "<html>" + text + "</html>";
    }

    public boolean waitForAnswer() throws InterruptedException {
        latch.await();
        return accepted.get();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        pageTitle = new JLabel();
        pageTitle.setHorizontalAlignment(0);
        pageTitle.setText("");
        root.add(pageTitle, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panelInfo = new JPanel();
        panelInfo.setLayout(new BorderLayout(0, 0));
        root.add(panelInfo, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelInfo.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        info = new JLabel();
        info.setHorizontalAlignment(0);
        info.setText("");
        panelInfo.add(info, BorderLayout.CENTER);
        final JScrollPane scrollPane = new JScrollPane();
        scrollPane.setHorizontalScrollBarPolicy(31);
        scrollPane.setVerticalScrollBarPolicy(20);
        root.add(scrollPane, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        scrollPane.setViewportView(content);
        final JPanel buttons = new JPanel();
        buttons.setLayout(new BorderLayout(0, 0));
        root.add(buttons, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        cancelAndExitButton = new JButton();
        cancelAndExitButton.setText("Cancel");
        buttons.add(cancelAndExitButton, BorderLayout.WEST);
        final JPanel rightButtons = new JPanel();
        rightButtons.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 0));
        buttons.add(rightButtons, BorderLayout.EAST);
        noButton = new JButton();
        noButton.setText("No");
        rightButtons.add(noButton);
        yesButton = new JButton();
        yesButton.setText("Yes");
        rightButtons.add(yesButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
